### ISSUE TITLE
Proposal: TrashBin

### ISSUE THREAD

**Issue by SandyXSD** [juicedata/juicefs#1057]
Data safety is always critical for a storage system. We should add TrashBin in JuiceFS and keep user-removed files for a certain period. Details below:

### How to Configure

Add a new option `--trash-days`  in `format` command to specify the days after which removed files will be permanently deleted.

- the default value is 1, which means files removed before 1 day will be automatically cleaned up
- use `--trash-days 0` to disable this feature; i.e, empty the trash now and make all removed files afterwards be cleaned up immediately
- run the `format` command again to change the configured value of days

### How to Use

The `.trash` directory should be located under root `/`, and is created automatically after volume formatted.

#### Remove

- Empty directory is removed as usual
- Non-directory file is moved to the `.trash`, under a sub-directory named by the date and hour that remove occurs
- File is rename as `{parent inode}-{file inode}-{original name}`, e.g, `1-10-test.txt`
- Data usage is not reduced until file is deleted from the `.trash`
- Move files directly into the `.trash` is not permitted

#### Browse

- All users can browse file list in `.trash`, and see files removed by others
- Removed file keeps its mode, so a user can still read it as long as he/she can read it previously, even if it's not remove by this user
- If mounted with `--subdir`, the whole `.trash` is still browsable, including files removed outside of the subdir

#### Restore/Delete

- Root user can restore a file by simply move it to another location outside of the `.trash`, without data copy
- Root user can permanently delete a file, and release its data storage in a short time
- Non-root users are not allowed to move or delete files in the `.trash`; however, they can still copy readable files to another location
  - Not decided yet, maybe should allow users to manipulate files owned by him/her?

#### Other

- All other operations that may change status of a file are not permitted, and should return `EPERM`

**Comment by Xuanwo** [comment]
Bravo work! I think it's the first formal proposal in juicefs community (please correct me!). We have taken a critical step forward.

## Lifecycle Feature

First of all, I want to discuss the feature itself. 

`lifecycle` is a widely used idea in storage systems, especially in object storage systems like s3 or oss. Lifecycle refers to a set of rules defined by the user that will apply to the objects that meet the requirements. For example:

- If the object is old than 30 days, move it to Standard-IA storage class (which is slower but much cheaper).
- If the object is old than 180 days, delete it.

From my point of view, the `TrashBin` feature is a special case of the lifecycle. We can define a status set of files/dirs like `active` and `trashed`. And we can add the ability for users to define the lifecycle rules so that users can add a new lifecycle that:

- If a file is becoming trashed, move it to `.trash` (just like this proposal did!)
- If a file is becoming trashed, move it to another storage system or another storage class.
- If a file is trashed and old than 30 days, delete it.

Based on lifecycle, we can implement features like `TrashBin` here, and users can define the rules on their own without hardcode `.trash` or adding new options like `--trash-days`.

More, lifecycle will give us more room for imagination. As we maintain the meta in juicefs, we will know the workload pattern, and we can know whether the file is hot, warm, or cold. So we can:

- If a file is becoming warm, move the underlying blocks to Standard-IA
- If a file is becoming cold, move the underlying blocks to Archive.
- Move all files under `/logs` to Archive.
- Move all files that were created 60 days ago to Archive.
- ...

Finally, juicefs will deliver to users the power of full data lifecycle management.

## TrashBin feature

According to this proposal, I have some questions:

> the default value is 1

The feature will be enabled by default? 

> run the `format` command again to change the configured value of days

`format` looks like a dangerous operation. Is it OK to change the config via `format`?

> The `.trash` directory should be located under root `/`

So the name of the trash directory is hardcoded to `.trash`? I noticed that we have many system files/dirs like `.trash`/`.accesslog` under juceifs. Maybe it is a good idea to move them into `.juice` folder to avoid conflict?

Maybe we need to make it clear that the `.trash` dir is under the root of the current juicefs root.

> File is rename as `{parent inode}-{file inode}-{original name}`, e.g, `1-10-test.txt`

The behavior is not as expected as a normal fs user. Maybe we need to refer to how windows/mac/KDE/gnome handles the trash bin?

---

Others LGTM.

One last note, this is an awesome proposal!

**Comment by Xuanwo** [comment]
BTW, maybe we can transfer this issue into a discussion?

**Comment by SandyXSD** [comment]
Firstly, the `TrashBin` is designed as a simple feature that helps users to get back un-intended deleted files, just for data safety. That's why it is enabled by default and has only one configuration. We treat it as a must-have before v1.0 released.

`LifeCycle`, on the other hand, is a more complex feature. It requires JuiceFS to manage multiple object storage systems in one volume (which is not supported yet), to provide an interface for users to customize the life cycle policy, etc. IMHO it's a nice-to-have for now, and would probably be into consideration after v1.0. Of course, you're welcome to raise a proposal now in the discussion channel so other people can share their opinions as well.

As for the questions:
> The feature will be enabled by default?

Yes, for data safety; old volumes have to enable it manually though (missing `thrash-days` is regarded as 0)

> `format` looks like a dangerous operation. Is it OK to change the config via `format`?

It's more like a temporary solution. Currently AKSK for object storage and volume quota (capacity & total inodes) are re-configured through the `format` command, which might be, yes, dangerous. I filed a new issue here:https://github.com/juicedata/juicefs/issues/1063

 > So the name of the trash directory is hardcoded to `.trash`?

Yes, all the system inodes (`.accesslog`, `.stats`, etc.) are hardcoded, and will always appear under the mounted root.

> The behavior is not as expected as a normal fs user. Maybe we need to refer to how windows/mac/KDE/gnome handles the trash bin?

The main reason here is to easily find all files under a certain directory before (use the parent inode prefix); adding a counter(Windows) or time(Mac) suffix doesn't help for this. It's still under discussion, please share it if you have other ideas, thanks.

**Comment by Xuanwo** [comment]
> The main reason here is to easily find all files under a certain directory before (use the parent inode prefix);

Can we involve the real user in this discussion? How will a real juicefs user restore his/her files from `.trash`? Take me as an example, I will use the filename and path to restore the file and never touch the inode during usage.

How about keeping the original name if there is no conflict, and adding inode id while conflict?

Other questions are resolved to me.

**Comment by SandyXSD** [comment]
We haven't found any better solution to keep original path information without impact on the performance of normal operations, so the design of naming is not touched. Users can simply ignore the inode prefix if they only care about the original name.
