### ISSUE TITLE
Support show the data cache ratio of the mount point

### ISSUE THREAD

**Issue by xiaogaozi** [juicedata/juicefs#1231]
**What would you like to be added**:

Support show the data cache ratio (not cache hit ratio) of the mount point, e.g.:

```sh
$ cat /jfs/.stats
...
juicefs_blockcache_ratio 0.9
...
```

The `juicefs_blockcache_ratio` is equal to `juicefs_blockcache_bytes / juicefs_used_space`.

**Why is this needed**:

Users may want to know what percentage of the current mount point data has been cached, and there is currently no way to quickly make this data available to users.

**Comment by davies** [comment]
The `juicefs_used_space`  is calculated using size of file, but `juicefs_blockcache_bytes` is calculated using size of blocks, so we can't provide the accurate ratio using `juicefs_blockcache_bytes / juicefs_used_space`.

Btw, since we already have both of them in `.stats`, so user can do the estimation by themself.
