### ISSUE TITLE
include function failure

### ISSUE THREAD

**Issue by fuhao009** [juicedata/juicefs#1542]
juicefs version 1.0.0-beta1 (2022-01-13T15:45:45Z 28a42cf)

CentOS Linux release 7.6.1810 (Core)

cmd: juicefs sync --debug --check-all --include '^20220309' xx1 xxx2

2022/03/09 17:43:46.896662 juicefs[7562] <DEBUG>: Creating file storage at endpoint /tmp/xxx1
2022/03/09 17:43:46.896742 juicefs[7562] <DEBUG>: Ensure directory /tmp
2022/03/09 17:43:46.896867 juicefs[7562] <DEBUG>: Creating file storage at endpoint /tmp/xxx2
2022/03/09 17:43:46.896889 juicefs[7562] <DEBUG>: Ensure directory /tmp
2022/03/09 17:43:46.897567 juicefs[7562] <INFO>: Syncing from file:///tmp/xxx1 to file:///tmp/xxx2
2022/03/09 17:43:46.897626 juicefs[7562] <DEBUG>: maxResults: 1000, defaultPartSize: 5242880, maxBlock: 10485760
2022/03/09 17:43:46.897644 juicefs[7562] <DEBUG>: Iterating objects from file:///tmp/xxx1 start ""
2022/03/09 17:43:46.897842 juicefs[7562] <DEBUG>: Iterating objects from file:///tmp/xxx2 start ""
2022/03/09 17:43:46.898115 juicefs[7562] <DEBUG>: Ignore directory /
2022/03/09 17:43:46.898458 juicefs[7562] <DEBUG>: Checked /20220309_989.ldb OK (and equal) in 86.454µs,
2022/03/09 17:43:46.898572 juicefs[7562] <DEBUG>: Checked /20220307_989.ldb OK (and equal) in 224.217µs,
2022/03/09 17:43:46.899825 juicefs[7562] <INFO>: Found: 2, copied: 0 (0 B), checked: 0 B, deleted: 0, skipped: 2, failed: 0

**Comment by zhijian-pro** [comment]
Please make sure `20220309_989.ldb` does not exist in the `xxx2` directory before executing the sync command, it will be skipped if it already exists

**Comment by zhijian-pro** [comment]
@fuhao009  The `sync --include` command did have some issues, we're working on a fix

**Comment by zhijian-pro** [comment]
Sorry, I was not very familiar with some of the logic before. After communicating with colleagues, we confirmed that there is no problem with this code. Our documentation is not clear enough to cause you to have problems using it.
You need to know the following two things:
1. If you want to express the concept of a folder in `SRC` or `DST`, please make sure that the path ends with "/" or "\", otherwise it will be considered as the prefix of the object name.
2. The `--include` option  need to be used with `--exclude PATTERN`.  It means only synchronize the set of objects remaining after excluding objects containing `exclude PATTERN` (POSIX regular expressions) from the set of objects containing `include PATTERN` (POSIX regular expressions).

**Comment by davies** [comment]
@fuhao009 We have changed the behavior of `--include` and `--exclude` to follow `rsync`, please build with latest main branch and try it out.
