### ISSUE TITLE
`juicefs status` command doesn't show `--read-only` sessions

### ISSUE THREAD

**Issue by solracsf** [juicedata/juicefs#2028]
**What happened**:

1) Mount 2 or more sessions, but at leasr one with `--read-only`
2) Issue a `juicefs status`. Session(s) with `--read-only` mount as param doesn't show up
3) Remount the same session(s) without `--read-only`; session(s) show up.

**What you expected to happen**:

All sessions should show up, regardless of their `rw/ro` mode.

**Environment**:
- JuiceFS version: `1.0.0-dev+2022-05-16.3558e726`

**Comment by suzaku** [comment]
This is the expected behavior of `juicefs status` as you can see in the help message of this subcommand.

`juicefs status` looks up sessions from the meta server. For example, if you are using `sqlite3`, a new record will be inserted into the `jfs_session2` table when a new session is created.
But `--read-only` is an exception, in `ReadOnly` mode, not even the session itself is written to the meta server.
