### ISSUE TITLE
Release juicefs hadoop sdk to maven repo

### ISSUE THREAD

**Issue by zuston** [juicedata/juicefs#2084]
I just want to use  the juicefs through hadoop sdk, but there is no it in maven repo.

**Comment by tangyoupeng** [comment]
Currently, juicefs-hadoop jar contains a library which is operating system dependent. 
In order to support multiple platform(linux, windows or mac os), we package libjfs.so, libjfs.dll, libjfs.dylib in the jar currently which cause the jar became so big. 
Current release jar support X86 architecture only.
There is also other architecture like arm which can cause the library double in order to support all platform. 

So, if we publish the currently released jar to maven central repo, it may cause some issues due to the operating system or the architecture difference. 

I suggest you maven install the jar packaged in your local machine before we find a proper way to publish the jar to maven central repo.

**Comment by zuston** [comment]
Thanks for your quick reply. I will follow your suggestion to use "mvn install" to my local machine.

Actually i just to debug the exception of "For input string: 256m" when using the juicefs hadoop jar.

**Comment by tangyoupeng** [comment]
it seems a configuration issuse, can you paste your core-site.xml here？

> Thanks for your quick reply. I will follow your suggestion to use "mvn install" to my local machine.
> 
> Actually i just to debug the exception of "For input string: 256m" when using the juicefs hadoop jar.

**Comment by zuston** [comment]
```java
....
<property>
  <name>fs.jfs.impl</name>
  <value>io.juicefs.JuiceFileSystem</value>
</property>
<property>
  <name>fs.AbstractFileSystem.jfs.impl</name>
  <value>io.juicefs.JuiceFS</value>
</property>
<property>
  <name>juicefs.myjfs.meta</name>
  <value>sqlite3:///root/myjfs.db</value>
</property>
```

**Comment by tangyoupeng** [comment]
@zuston 
We've package all needed binary in one jar and publish the jar to maven center repo.
Refer to [java project](https://juicefs.com/docs/community/hadoop_java_sdk/#javascala-project)
