### ISSUE TITLE
Interrupted uploads may result in "object leaks"

### ISSUE THREAD

**Issue by yuhr123** [juicedata/juicefs#2987]
**What happened**:
When copying large files to the file system, the copy operation is interrupted manually and an object leak can occur.

**What you expected to happen**:
Avoiding object leaks

**How to reproduce it (as minimally and precisely as possible)**:
Manually interrupting a copy operation

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.0.2+2022-10-13.514ef03
- Cloud provider or hardware configuration running JuiceFS: normal pc
- OS (e.g `cat /etc/os-release`): Ubuntu 22.04.1
- Kernel (e.g. `uname -a`): Linux homenas 5.15.0-52-generic
- Object storage (cloud provider and region, or self maintained): b2
- Metadata engine info (version, cloud provider managed or self maintained): sqlite3
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
This happens when the network is particularly bad. Because juicefs is still trying to upload to the object store after the terminal copy.
To avoid intermediate files being misidentified as leaked objects, the juicefs gc defaults to skipping files uploaded within the last hour. The `JFS_GC_SKIPPEDTIME` environment variable can change this value.
