### ISSUE TITLE
How to change the underlying object storage of an existing file system?

### ISSUE THREAD

**Issue by youyongsong** [juicedata/juicefs#3191]
I'm using juicefs in my company's internal k8s cluster to provide pv storage, and it's been working perfectly fine so far👍.
I use redis as the metadata engine and self-hosted minio as object storage, but for some reason the machine where minio is located will be recycled and a new minio machine will be provided. I have completed the data synchronization of two minio clusters, and I want to replace the underlying minio of the currently used juicefs file system with the new minio cluster. Is there any document that can guide me to complete the replacement of object storage?

**Comment by SandyXSD** [comment]
Usually it's not recommended to switch underlying object storage because it may cause data corruption/loss if not operated properly. However, if you do want to do this, it's workable with the following steps:
1. unmount/disconnect all clients. (you may run `juicefs status META-URL` to make sure there's no active session)
2. fully sync the two object storage, as you already did
3. change the address of minio with the [`juicefs config --bucket xxx`](https://juicefs.com/docs/community/command_reference/#juicefs-config) command. You may also modify the AKSK at the same time if needed
4. mount the clients, and do some check to see if everything works as expected

**Comment by youyongsong** [comment]
Thank you very much for your reply. I have completed the replacement of minio according to your suggestion, and everything works as expected!
