### ISSUE TITLE
can't support trino as trino plugin interface name is changed from presto to trino.

### ISSUE THREAD

**Issue by bronzels** [juicedata/juicefs#3238]
**What would you like to be added**:
Currently can't support trino as trino plugin interface name is changed from presto to trino. Suggest implement renamed trino interface to support trino.

**Why is this needed**:
Trino is more popular than prestodb at least in China. Both are used for fast access to hive data.

**Comment by tangyoupeng** [comment]
place the juicefs-hadoop.jar in trino/plugin/hive

**Comment by kay120** [comment]
I put juicefs-hadoop-1.0.3.jar in trino/plugin/hive ,but have the problem  as this:
"Query 20230321_100322_00000_82hx5 failed: class io.juicefs.JuiceFileSystemImpl$FileInputStream (in unnamed module @0x6ca1c156) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x6ca1c156"

Can you help me?Thank you @tangyoupeng

**Comment by kay120** [comment]
add  
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED  
to jvm.config is ok
