### ISSUE TITLE
Progress bar for fsck

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#336]
It will take a long time to list all the blocks, we should show the progress rather waiting blindly.

**Comment by zhijian-pro** [comment]
![Kapture 2021-07-24 at 17 44 34](https://user-images.githubusercontent.com/31313340/126865284-b2078c6d-6b3c-421a-abac-dce57d5c9e05.gif)
@davies How does this work dynamically? If the program is currently ListSlices, there will be a dynamic icon spinning behind it, and if the ListSlices are finished, the icon will disappear.
In addition, there is no performance loss because the total is not obtained.
Different types of metadata are displayed and handled in the same way

But for the ListSlices interface I added a parameter bar *mpb.Bar which can be passed as nil when the status display is not needed

Is this solution acceptable?

**Comment by davies** [comment]
This one looks good. W can pass a `updateProgress func (n int64)` to ListSlices

**Comment by davies** [comment]
Fixed by #683
