### ISSUE TITLE
user privilege escalation bug (#13976) https://github.com/minio/minio/pull/13976

### ISSUE THREAD

**Issue by gongxulei** [juicedata/juicefs#4120]
https://github.com/minio/minio/pull/13976

**Comment by davies** [comment]
@gongxulei Do you hit by this bug using the builtin gateway or the full-feature one?

**Comment by gongxulei** [comment]
> @gongxulei Do you hit by this bug using the builtin gateway or the full-feature one?

Thanks for the answer, I've been doing some security work lately, and when I was doing a binary vulnerability scan, I found this issue, I looked at all the released juicefs versions, none of which merged this patch, but actually the minio community has fixed this bug a long time ago.

**Comment by zhijian-pro** [comment]
1. This api will never be registered in our built-in version of gateway. So, the built-in gateway of juicefs does not have this problem at present.
<img width="1277" alt="image" src="https://github.com/juicedata/juicefs/assets/31313340/724570ea-61a0-40b6-9b57-e43851d9b0ef">
2. The full-feature juicefs gateway about https://github.com/juicedata/minio will not have this problem, because it contains a fix the commit.
