### ISSUE TITLE
Question: how does JuiceFS interact with S3?

### ISSUE THREAD

**Issue by waynerobinson** [juicedata/juicefs#44]
Is it possible to get some more info on how JuiceFS interacts with S3?

Primarily, I'm interested in when a read and write occurs to S3 vs Redis? 

Some background… whilst S3 is an amazing object store, it's per request costs ($5/million writes and $0.40 per million reads) can be extremely expensive if you're dealing with lots of tiny objects.

With regards to the chunking/slicing that JuiceFS performs, does this mean writing a lot of small files at once results in only a few S3 put operations and reading them back in write-order would result in only a few reads?

Thanks in advance and I'm excited to keep an eye on this project. 👍

**Comment by davies** [comment]
Currently, JuiceFS does NOT merge small files together to reduce the PUT calls, because that will slow down future read and make it harder the manage the life cycle of data. We had tried this before, it does not work well, so abandoned. 

JuiceFS could cached the small files in your local disk, if you read them frequently. So it can reduce the cost for GET requests.

**Comment by waynerobinson** [comment]
Thank you for the quick confirmation. 

I understand your comments about making lifecycle management more complicated. 

However, S3 supports range-based retrievals. So it should actually be possible to make retrievals across multiple S3 sub-objects faster as you could parallelise the range reads across multiple objects.

**Comment by davies** [comment]
That's true if we disable the compression in JuiceFS.  But the caching is still a problem, for example, in order to cache a tiny file, you have to cache all the other files in same 4MB block.
