### ISSUE TITLE
Can juicefs build distributed storage clusters using local disks instead of s3 object storage as block file storage

### ISSUE THREAD

**Issue by vitaaaaa1** [juicedata/juicefs#5228]
Can juicefs build distributed storage clusters using local disks instead of s3 object storage as block file storage

**Comment by SandyXSD** [comment]
Using local disks directly is only for TEST purpose, since clients on other nodes can’t access these disks. You have to build a distributed object storage (MinIO, Ceph Rados, etc.) on the disks first.

More details can be found here: https://juicefs.com/docs/community/reference/how_to_set_up_object_storage#local-disk.

**Comment by vitaaaaa1** [comment]
> Using local disks directly is only for TEST purpose, since clients on other nodes can’t access these disks. You have to build a distributed object storage (MinIO, Ceph Rados, etc.) on the disks first.
> 
> More details can be found here: https://juicefs.com/docs/community/reference/how_to_set_up_object_storage#local-disk.

Thank you for your response. I have another new question.
If I use the single-node mode, can I mount multiple disks to achieve the purpose of data redundancy?
For example, if one disk fails, the other disks can recover the data using error-correcting codes or other methods.
In essence, I want to achieve data redundancy without using object storage.
