### ISSUE TITLE
Cleanup current session after umounted

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#792]
After a mount point umounted, there is still a session in database, will be cleaned by other clients.

We should cleanup it ASAP.

**Comment by SandyXSD** [comment]
What JuiceFS do when cleaning a stale session:
1. delete all sustained inodes, and the files
2. delete all related locks
3. delete session & sessionInfo entry

Since we need the session entry to find the sid required for 1 & 2, it must be deleted at last. It seems this issue is more complicated than we thought :<
