### ISSUE TITLE
Supported Apache Ozone Object Storage

### ISSUE THREAD

**Issue by lunescode** [juicedata/juicefs#964]
**What would you like to be added**:
Object Storage Suport Apache Ozone.

**Why is this needed**:
Apache Ozone is new generation storage for hadoop, Now goofys can suport , So We Suggest juicefs also suport!

**Comment by SandyXSD** [comment]
It can be used through S3 SDK since Ozone is S3 compatible:
https://ci-hadoop.apache.org/view/Hadoop%20Ozone/job/ozone-doc-master/lastSuccessfulBuild/artifact/hadoop-hdds/docs/public/interface/s3.html

We'd better add a section [here](https://github.com/juicedata/juicefs/blob/main/docs/en/how_to_setup_object_storage.md#supported-object-storage) for it though. Do you want to write it?

**Comment by zhijian-pro** [comment]
After testing, we support Apache Ozone, you can use through  S3 compatible mode.
It should be noted that we do not support s3 storage-class, so ozone needs to set up multiple replicas, more configuration please refer to [Apache Ozone documentation](https://ozone.apache.org/docs/1.2.1/start/startfromdockerhub.html)
